object Versions {

    const val coreKtx="1.12.0"
    const val lifecycleKtx="2.6.2"
    const val activityCompose="1.8.2"
    const val composeBom="2023.03.00"
    const val nav_version="2.7.6"
    const val espresso="3.5.1"
    const val jUnit="4.13.2"
    const val extJUnit="1.1.5"
    const val lifecycle_version="2.6.2"
    const val appcompat="1.6.1"
    const val material="1.11.0"
    const val hiltAndroid="2.44"
    const val hiltCompiler="1.1.0"
    const val hiltLifeCycleViewmodel="1.0.0-alpha03"
    const val hiltNavigationCompose="1.1.0"
    const val retrofit="2.9.0"
    const val okHttp="5.0.0-alpha.2"
    const val moshi="1.14.0"
    const val moshiConverter="2.9.0"
    const val loggingInterceptor="4.8.1"
    const val coroutineCore="1.8.0-RC2"
}